-- V1_create_seconde-residence_table --

CREATE TABLE second_residences
(
    id         bigint                 NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    street     character varying(255) NOT NULL,
    city       character varying(100) NOT NULL,
    zip_code   character varying(50)  NOT NULL
);

ALTER TABLE second_residences
ALTER
COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
      SEQUENCE NAME second_residences_id_seq
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1
      );

ALTER TABLE second_residences
    ADD CONSTRAINT second_residences_pkey PRIMARY KEY (id);