INSERT INTO "categories" ("id", "name_category", "created_at", "updated_at")
VALUES (1, 'Informatique', NOW(), NOW()),
       (2, 'Outils', NOW(), NOW()),
       (3, 'Réparation de verre', NOW(), NOW()),
       (4, 'Composants électroniques', NOW(), NOW()),
       (5, 'Sécurité', NOW(), NOW()),
       (6, 'Jardinage', NOW(), NOW()),
       (7, 'Peinture', NOW(), NOW()),
       (8, 'Bricolage', NOW(), NOW()),
       (9, 'Éclairage', NOW(), NOW()),
       (10, 'Plomberie', NOW(), NOW()),
       (11, 'Électroménager', NOW(), NOW()),
       (12, 'Énergie', NOW(), NOW()),
       (13, 'Chauffage et climatisation', NOW(), NOW()),
       (14, 'Construction', NOW(), NOW()),
       (15, 'Automobile', NOW(), NOW()),
       (16, 'Meubles', NOW(), NOW()),
       (17, 'Équipements sportifs', NOW(), NOW()),
       (18, 'Bricolage électromécanique', NOW(), NOW()),
       (19, 'Accessoires de cuisine', NOW(), NOW()),
       (20, 'Vêtements et équipements de sécurité', NOW(), NOW()),
       (21, 'Accessoires de bureau', NOW(), NOW()),
       (22, 'Cadeaux et décorations', NOW(), NOW()),
       (23, 'Équipements audio', NOW(), NOW()),
       (24, 'Camping et randonnée', NOW(), NOW()),
       (25, 'Vélo et accessoires', NOW(), NOW()),
       (26, 'Ferroviaire', NOW(), NOW()),
       (27, 'Produits de nettoyage', NOW(), NOW()),
       (28, 'Outils pour bois', NOW(), NOW()),
       (29, 'Outils pour métal', NOW(), NOW()),
       (30, 'Équipements de jardinage électrique', NOW(), NOW()),
       (31, 'Services de réparation', NOW(), NOW()),
       (32, 'Services de nettoyage', NOW(), NOW()),
       (33, 'Services de rénovation', NOW(), NOW()),
       (34, 'Services de construction', NOW(), NOW()),
       (35, 'Services informatiques', NOW(), NOW()),
       (36, 'Services de jardinage', NOW(), NOW()),
       (37, 'Services de plomberie', NOW(), NOW()),
       (38, 'Services d’électricité', NOW(), NOW()),
       (39, 'Services automobile', NOW(), NOW()),
       (40, 'Services d’entretien', NOW(), NOW()),
       (41, 'Livraison et transport', NOW(), NOW()),
       (42, 'Événementiel', NOW(), NOW()),
       (43, 'Gestion de projet', NOW(), NOW()),
       (44, 'Conseil en management', NOW(), NOW()),
       (45, 'Consultation juridique', NOW(), NOW()),
       (46, 'Consultation financière', NOW(), NOW()),
       (47, 'Services de traduction', NOW(), NOW()),
       (48, 'Services de photographie', NOW(), NOW()),
       (49, 'Design graphique', NOW(), NOW()),
       (50, 'Web design', NOW(), NOW()),
       (51, 'Création de contenu vidéo', NOW(), NOW()),
       (52, 'Marketing digital', NOW(), NOW()),
       (53, 'Rédaction web', NOW(), NOW()),
       (54, 'Services d’assistance virtuelle', NOW(), NOW()),
       (55, 'Création de sites web', NOW(), NOW()),
       (56, 'SEO (optimisation de site)', NOW(), NOW()),
       (57, 'Publicité en ligne', NOW(), NOW()),
       (58, 'Services de comptabilité', NOW(), NOW()),
       (59, 'Aide à la rédaction de CV', NOW(), NOW()),
       (60, 'Services de coaching personnel', NOW(), NOW()),
       (61, 'Coaching professionnel', NOW(), NOW()),
       (62, 'Formation en ligne', NOW(), NOW()),
       (63, 'Cours particuliers', NOW(), NOW()),
       (64, 'Accompagnement scolaire', NOW(), NOW()),
       (65, 'Développement personnel', NOW(), NOW()),
       (66, 'Création d’application mobile', NOW(), NOW()),
       (67, 'Audit énergétique', NOW(), NOW()),
       (68, 'Construction de piscine', NOW(), NOW()),
       (69, 'Nettoyage après sinistre', NOW(), NOW()),
       (70, 'Réparation de toiture', NOW(), NOW()),
       (71, 'Peinture extérieure', NOW(), NOW()),
       (72, 'Aménagement paysager', NOW(), NOW()),
       (73, 'Débouchage de canalisations', NOW(), NOW()),
       (74, 'Soutien psychologique', NOW(), NOW()),
       (75, 'Soutien à la parentalité', NOW(), NOW()),
       (76, 'Aide aux devoirs', NOW(), NOW()),
       (77, 'Services d’assistance informatique', NOW(), NOW()),
       (78, 'Accompagnement en nutrition', NOW(), NOW()),
       (79, 'Gestion des réseaux sociaux', NOW(), NOW()),
       (80, 'Création de logos', NOW(), NOW());