INSERT INTO materials (id, name_material, description_material, price_hour_material, state_material, category_id,
                       is_available, created_at, updated_at)
VALUES (1, 'Ordinateur portable', 'Ordinateur portable haute performance pour la programmation.', 25.00, 'GOOD_STATE',
        1, true, NOW(), NOW()),
       (2, 'PC de bureau', 'Ordinateur de bureau puissant pour le jeu et le design.', 30.00, 'GOOD_STATE', 1, true,
        NOW(), NOW()),
       (3, 'Écran 4K', 'Moniteur 4K de 27 pouces pour un affichage haute résolution.', 15.00, 'GOOD_STATE', 1, true,
        NOW(), NOW()),
       (4, 'Clavier mécanique', 'Clavier mécanique pour un confort de frappe.', 5.00, 'GOOD_STATE', 1, true, NOW(),
        NOW()),
       (5, 'Souris sans fil', 'Souris sans fil pour une navigation facile.', 4.00, 'GOOD_STATE', 1, true, NOW(), NOW()),
       (6, 'Routeur Wi-Fi', 'Routeur haut débit pour la connectivité Internet.', 10.00, 'GOOD_STATE', 1, true, NOW(),
        NOW()),
       (7, 'Commutateur réseau', 'Commutateur pour connecter plusieurs appareils.', 12.00, 'GOOD_STATE', 1, true, NOW(),
        NOW()),
       (8, 'Disque dur externe', 'Disque dur externe pour le stockage de données.', 20.00, 'GOOD_STATE', 1, true, NOW(),
        NOW()),
       (9, 'SSD', 'Disque SSD pour un accès plus rapide aux données.', 18.00, 'GOOD_STATE', 1, true, NOW(), NOW()),
       (10, 'Alimentation PC', 'Alimentation fiable pour ordinateurs.', 15.00, 'GOOD_STATE', 1, true, NOW(), NOW()),
       (11, 'Perceuse sans fil', 'Perceuse sans fil pour divers travaux.', 20.00, 'GOOD_STATE', 2, true, NOW(), NOW()),
       (12, 'Clé dynamométrique', 'Clé dynamométrique de précision pour un serrage exact.', 25.00, 'GOOD_STATE', 2,
        true, NOW(), NOW()),
       (13, 'Tournevis', 'Tournevis de haute qualité pour des travaux précis.', 3.00, 'GOOD_STATE', 2, true, NOW(),
        NOW()),
       (14, 'Scie circulaire', 'Scie à moteur pour découper des matériaux épais.', 15.00, 'GOOD_STATE', 2, true, NOW(),
        NOW()),
       (15, 'Cric hydraulique', 'Cric hydraulique pour soulever des véhicules.', 25.00, 'GOOD_STATE', 2, true, NOW(),
        NOW()),
       (16, 'Couteau à mastic', 'Outil pour appliquer le mastic lors des réparations de verre.', 6.00, 'GOOD_STATE', 3,
        true, NOW(), NOW()),
       (17, 'Ventouse pour verre', 'Ventouse pour manipuler le verre en toute sécurité.', 5.00, 'GOOD_STATE', 3, true,
        NOW(), NOW()),
       (18, 'Nettoyant pour verre', 'Nettoyant spécialisé pour surfaces vitrées.', 3.00, 'GOOD_STATE', 3, true, NOW(),
        NOW()),
       (19, 'Lunettes de sécurité', 'Lunettes de protection pour les travaux sur verre.', 4.00, 'GOOD_STATE', 3, true,
        NOW(), NOW()),
       (20, 'Cutter pour verre', 'Cutter spécialisé pour couper du verre.', 7.00, 'GOOD_STATE', 3, true, NOW(), NOW()),

       (21, 'Casque de sécurité', 'Casque de protection pour éviter les blessures.', 12.00, 'GOOD_STATE', 5, true,
        NOW(), NOW()),
       (22, 'Gants de travail', 'Gants résistants pour travailler en toute sécurité.', 5.00, 'GOOD_STATE', 5, true,
        NOW(), NOW()),
       (23, 'Masque de protection', 'Masque pour se protéger des poussières et des gaz nocifs.', 3.50, 'GOOD_STATE', 5,
        true, NOW(), NOW()),
       (24, 'Vêtements de travail', 'Vêtements robustes pour les travaux manuels.', 8.00, 'GOOD_STATE', 5, true, NOW(),
        NOW()),
       (25, 'Bottes de sécurité', 'Bottes en cuir renforcées pour protéger les pieds.', 10.00, 'GOOD_STATE', 5, true,
        NOW(), NOW()),
       (26, 'Pelle de jardin', 'Outil pour creuser et déplacer la terre.', 6.00, 'GOOD_STATE', 6, true, NOW(), NOW()),
       (27, 'Râteau', 'Râteau pour niveler la terre et ramasser les feuilles.', 7.00, 'GOOD_STATE', 6, true, NOW(),
        NOW()),
       (28, 'Tondeuse à gazon', 'Tondeuse électrique pour une pelouse bien entretenue.', 18.00, 'GOOD_STATE', 6, true,
        NOW(), NOW()),
       (29, 'Arrosoir', 'Arrosoir pour arroser les plantes.', 3.00, 'GOOD_STATE', 6, true, NOW(), NOW()),
       (30, 'Tronçonneuse', 'Tronçonneuse électrique pour couper les branches d’arbres.', 25.00, 'GOOD_STATE', 6, true,
        NOW(), NOW()),
       (31, 'Pince', 'Pince pour couper et saisir des objets.', 4.00, 'GOOD_STATE', 2, true, NOW(), NOW()),
       (32, 'Serre-joint', 'Serre-joint pour maintenir les pièces en place lors de travaux.', 5.00, 'GOOD_STATE', 2,
        true, NOW(), NOW()),
       (33, 'Scie à main', 'Scie manuelle pour couper du bois et des matériaux fins.', 8.00, 'GOOD_STATE', 2, true,
        NOW(), NOW()),
       (34, 'Mèche à bois', 'Mèche pour percer des trous dans le bois.', 2.50, 'GOOD_STATE', 2, true, NOW(), NOW()),
       (35, 'Meuleuse', 'Meuleuse pour découper et polir les métaux.', 20.00, 'GOOD_STATE', 2, true, NOW(), NOW()),
       (36, 'Mètre ruban', 'Mètre ruban pour mesurer des distances.', 2.00, 'GOOD_STATE', 2, true, NOW(), NOW()),
       (37, 'Visseuse', 'Visseuse électrique pour visser rapidement les matériaux.', 15.00, 'GOOD_STATE', 2, true,
        NOW(), NOW()),
       (38, 'Film de protection', 'Film pour protéger les surfaces vitrées des rayures.', 5.00, 'GOOD_STATE', 3, true,
        NOW(), NOW()),
       (39, 'Pistolet à colle', 'Pistolet à colle chaude pour fixer les objets sur le verre.', 7.00, 'GOOD_STATE', 3,
        true, NOW(), NOW()),
       (40, 'Résistance', 'Résistance pour circuit électronique.', 3.00, 'GOOD_STATE', 4, true, NOW(), NOW()),
       (41, 'Carte mère', 'Carte mère pour ordinateur de bureau.', 50.00, 'GOOD_STATE', 4, true, NOW(), NOW()),
       (42, 'Gilet pare-balles', 'Gilet de protection contre les projectiles.', 40.00, 'GOOD_STATE', 5, true, NOW(),
        NOW()),
       (43, 'Cloison de sécurité', 'Cloison mobile pour délimiter des zones de sécurité.', 12.00, 'GOOD_STATE', 5, true,
        NOW(), NOW()),
       (44, 'Taille-haie', 'Taille-haie électrique pour couper les haies.', 18.00, 'GOOD_STATE', 6, true, NOW(), NOW()),
       (45, 'Tracteur tondeuse', 'Tracteur tondeuse pour grandes surfaces de pelouse.', 35.00, 'GOOD_STATE', 6, true,
        NOW(), NOW()),
       (46, 'Pinceau', 'Pinceau pour application de peinture.', 2.50, 'GOOD_STATE', 7, true, NOW(), NOW()),
       (47, 'Rouleau de peinture', 'Rouleau pour une application uniforme de la peinture.', 4.00, 'GOOD_STATE', 7, true,
        NOW(), NOW()),
       (48, 'Scie à onglet', 'Scie à onglet pour effectuer des découpes précises.', 12.00, 'GOOD_STATE', 8, true, NOW(),
        NOW()),
       (49, 'Colle universelle', 'Colle forte pour assembler divers matériaux.', 3.50, 'GOOD_STATE', 8, true, NOW(),
        NOW()),
       (50, 'Lampe LED', 'Lampe LED pour un éclairage économique.', 5.00, 'GOOD_STATE', 9, true, NOW(), NOW()),
       (51, 'Projecteur', 'Projecteur puissant pour éclairage extérieur.', 10.00, 'GOOD_STATE', 9, true, NOW(), NOW()),
       (52, 'Clé à molette', 'Clé à molette pour serrer ou desserrer les écrous.', 4.00, 'GOOD_STATE', 10, true, NOW(),
        NOW()),
       (53, 'Tuyau PVC', 'Tuyau PVC pour installations sanitaires.', 8.00, 'GOOD_STATE', 10, true, NOW(), NOW()),
       (54, 'Réfrigérateur', 'Réfrigérateur avec congélateur intégré.', 20.00, 'GOOD_STATE', 11, true, NOW(), NOW()),
       (55, 'Micro-ondes', 'Four à micro-ondes pour réchauffer les aliments rapidement.', 12.00, 'GOOD_STATE', 11, true,
        NOW(), NOW()),
       (56, 'Panneau solaire', 'Panneau solaire pour la production d\''énergie.', 30.00, 'GOOD_STATE', 12, true, NOW(),
        NOW()),
       (57, 'Batterie de stockage', 'Batterie pour stocker l\''énergie produite par des panneaux solaires.', 40.00,
        'GOOD_STATE', 12, true, NOW(), NOW()),
       (58, 'Climatiseur portable', 'Climatiseur mobile pour maintenir une température agréable.', 25.00, 'GOOD_STATE',
        13, true, NOW(), NOW()),
       (59, 'Radiateur électrique', 'Radiateur électrique pour chauffer une pièce rapidement.', 15.00, 'GOOD_STATE', 13,
        true, NOW(), NOW()),
       (60, 'Parpaing', 'Parpaing pour la construction de murs et fondations.', 8.00, 'GOOD_STATE', 14, true, NOW(),
        NOW()),
       (61, 'Ciment', 'Ciment pour la fabrication de béton.', 5.00, 'GOOD_STATE', 14, true, NOW(), NOW()),
       (62, 'Jante', 'Jante en alliage pour voiture.', 25.00, 'GOOD_STATE', 15, true, NOW(), NOW()),
       (63, 'Pneu', 'Pneu de voiture adapté à toutes saisons.', 15.00, 'GOOD_STATE', 15, true, NOW(), NOW()),
       (64, 'Chaise de bureau', 'Chaise ergonomique pour le travail de bureau.', 10.00, 'GOOD_STATE', 16, true, NOW(),
        NOW()),
       (65, 'Table de travail', 'Table de travail avec plusieurs tiroirs.', 20.00, 'GOOD_STATE', 16, true, NOW(),
        NOW()),
       (66, 'Raquette de tennis', 'Raquette légère pour jouer au tennis.', 8.00, 'GOOD_STATE', 17, true, NOW(), NOW()),
       (67, 'Vélo de course', 'Vélo de course pour performance optimale.', 15.00, 'GOOD_STATE', 17, true, NOW(), NOW()),
       (68, 'Lego', 'Jeu de construction de blocs Lego.', 5.00, 'GOOD_STATE', 18, true, NOW(), NOW()),
       (69, 'Poupée', 'Poupée en peluche douce et câline.', 3.00, 'GOOD_STATE', 18, true, NOW(), NOW()),
       (70, 'T-shirt', 'T-shirt en coton doux pour l\''été.', 2.50, 'GOOD_STATE', 19, true, NOW(), NOW()),
       (71, 'Pantalon', 'Pantalon en toile pour un confort optimal.', 4.00, 'GOOD_STATE', 19, true, NOW(), NOW()),
       (72, 'Montre', 'Montre en cuir, élégante et moderne.', 10.00, 'GOOD_STATE', 20, true, NOW(), NOW()),
       (73, 'Sac à main', 'Sac à main chic en cuir.', 15.00, 'GOOD_STATE', 20, true, NOW(), NOW()),
       (74, 'Chaussettes', 'Chaussettes en coton, confortables et respirantes.', 1.00, 'GOOD_STATE', 30, true, NOW(),
        NOW()),
       (75, 'Chaise pliante', 'Chaise légère et pratique, idéale pour les pique-niques.', 4.00, 'GOOD_STATE', 30, true,
        NOW(), NOW()),
       (76, 'Tente de camping', 'Tente pour deux personnes, facile à monter.', 20.00, 'GOOD_STATE', 30, true, NOW(),
        NOW()),
       (77, 'Rouleau de film plastique', 'Film plastique pour protéger les surfaces.', 2.50, 'GOOD_STATE', 30, true,
        NOW(), NOW()),
       (78, 'Corde', 'Corde résistante pour différents usages.', 3.00, 'GOOD_STATE', 30, true, NOW(), NOW()),
       (79, 'Chaise de jardin', 'Chaise en plastique pour jardin ou terrasse.', 5.00, 'GOOD_STATE', 30, true, NOW(),
        NOW()),
       (80, 'Trousse de premiers secours', 'Trousse de premiers secours complète pour les urgences.', 10.00,
        'GOOD_STATE', 30, true, NOW(), NOW());