INSERT INTO materials (id, name_material, category_id,
                       is_available, created_at, updated_at)
VALUES (1, 'Ordinateur portable',
        1, true, NOW(), NOW()),
       (2, 'PC de bureau', 1, true,
        NOW(), NOW()),
       (3, 'Écran 4K', 1, true,
        NOW(), NOW()),
       (4, 'Clavier mécanique', 1, true, NOW(),
        NOW()),
       (5, 'Souris sans fil', 1, true, NOW(), NOW()),
       (6, 'Routeur Wi-Fi', 1, true, NOW(),
        NOW()),
       (7, 'Commutateur réseau', 1, true, NOW(),
        NOW()),
       (8, 'Disque dur externe', 1, true, NOW(),
        NOW()),
       (9, 'SSD', 1, true, NOW(), NOW()),
       (10, 'Alimentation PC', 1, true, NOW(), NOW()),
       (11, 'Perceuse sans fil', 2, true, NOW(), NOW()),
       (12, 'Clé dynamométrique', 2,
        true, NOW(), NOW()),
       (13, 'Tournevis', 2, true, NOW(),
        NOW()),
       (14, 'Scie circulaire', 2, true, NOW(),
        NOW()),
       (15, 'Cric hydraulique', 2, true, NOW(),
        NOW()),
       (16, 'Couteau à mastic',3,
        true, NOW(), NOW()),
       (17, 'Ventouse pour verre', 3, true,
        NOW(), NOW()),
       (18, 'Nettoyant pour verre', 3, true, NOW(),
        NOW()),
       (19, 'Lunettes de sécurité', 3, true,
        NOW(), NOW()),
       (20, 'Cutter pour verre', 3, true, NOW(), NOW()),

       (21, 'Casque de sécurité', 5, true,
        NOW(), NOW()),
       (22, 'Gants de travail', 5, true,
        NOW(), NOW()),
       (23, 'Masque de protection',5,
        true, NOW(), NOW()),
       (24, 'Vêtements de travail', 5, true, NOW(),
        NOW()),
       (25, 'Bottes de sécurité', 5, true,
        NOW(), NOW()),
       (26, 'Pelle de jardin', 6, true, NOW(), NOW()),
       (27, 'Râteau', 6, true, NOW(),
        NOW()),
       (28, 'Tondeuse à gazon', 6, true,
        NOW(), NOW()),
       (29, 'Arrosoir', 6, true, NOW(), NOW()),
       (30, 'Tronçonneuse', 6, true,
        NOW(), NOW()),
       (31, 'Pince', 2, true, NOW(), NOW()),
       (32, 'Serre-joint', 2,
        true, NOW(), NOW()),
       (33, 'Scie à main', 2, true,
        NOW(), NOW()),
       (34, 'Mèche à bois', 2, true, NOW(), NOW()),
       (35, 'Meuleuse', 2, true, NOW(), NOW()),
       (36, 'Mètre ruban', 2, true, NOW(), NOW()),
       (37, 'Visseuse', 2, true,
        NOW(), NOW()),
       (38, 'Film de protection', 3, true,
        NOW(), NOW()),
       (39, 'Pistolet à colle', 3,
        true, NOW(), NOW()),
       (40, 'Résistance', 4, true, NOW(), NOW()),
       (41, 'Carte mère', 4, true, NOW(), NOW()),
       (42, 'Gilet pare-balles', 5, true, NOW(),
        NOW()),
       (43, 'Cloison de sécurité', 5, true,
        NOW(), NOW()),
       (44, 'Taille-haie', 6, true, NOW(), NOW()),
       (45, 'Tracteur tondeuse', 6, true,
        NOW(), NOW()),
       (46, 'Pinceau', 7, true, NOW(), NOW()),
       (47, 'Rouleau de peinture', 7, true,
        NOW(), NOW()),
       (48, 'Scie à onglet', 8, true, NOW(),
        NOW()),
       (49, 'Colle universelle', 8, true, NOW(),
        NOW()),
       (50, 'Lampe LED', 9, true, NOW(), NOW()),
       (51, 'Projecteur', 9, true, NOW(), NOW()),
       (52, 'Clé à molette', 10, true, NOW(),
        NOW()),
       (53, 'Tuyau PVC', 10, true, NOW(), NOW()),
       (54, 'Réfrigérateur', 11, true, NOW(), NOW()),
       (55, 'Micro-ondes', 11, true,
        NOW(), NOW()),
       (56, 'Panneau solaire', 12, true, NOW(),
        NOW()),
       (57, 'Batterie de stockage', 12, true, NOW(), NOW()),
       (58, 'Climatiseur portable',
        13, true, NOW(), NOW()),
       (59, 'Radiateur électrique', 13,
        true, NOW(), NOW()),
       (60, 'Parpaing', 14, true, NOW(),
        NOW()),
       (61, 'Ciment', 14, true, NOW(), NOW()),
       (62, 'Jante', 15, true, NOW(), NOW()),
       (63, 'Pneu', 15, true, NOW(), NOW()),
       (64, 'Chaise de bureau', 16, true, NOW(),
        NOW()),
       (65, 'Table de travail', 16, true, NOW(),
        NOW()),
       (66, 'Raquette de tennis', 17, true, NOW(), NOW()),
       (67, 'Vélo de course', 17, true, NOW(), NOW()),
       (68, 'Lego', 18, true, NOW(), NOW()),
       (69, 'Poupée', 18, true, NOW(), NOW()),
       (70, 'T-shirt', 19, true, NOW(), NOW()),
       (71, 'Pantalon', 19, true, NOW(), NOW()),
       (72, 'Montre', 20, true, NOW(), NOW()),
       (73, 'Sac à main', 20, true, NOW(), NOW()),
       (74, 'Chaussettes', 30, true, NOW(),
        NOW()),
       (75, 'Chaise pliante', 30, true,
        NOW(), NOW()),
       (76, 'Tente de camping', 30, true, NOW(),
        NOW()),
       (77, 'Rouleau de film plastique', 30, true,
        NOW(), NOW()),
       (78, 'Corde', 30, true, NOW(), NOW()),
       (79, 'Chaise de jardin', 30, true, NOW(),
        NOW()),
       (80, 'Trousse de premiers secours', 30, true, NOW(), NOW());