INSERT INTO materials (id, name_material, description_material, price_hour_material, state_material, category_id,
                       is_available, created_at, updated_at)
VALUES (1, 'Ordinateur portable', 'Ordinateur portable haute performance pour la programmation.', 25.00, 'GOOD_STATE',
        1, true, NOW(), NOW()),
       (2, 'PC de bureau', 'Ordinateur de bureau puissant pour le jeu et le design.', 30.00, 'GOOD_STATE', 1, true,
        NOW(), NOW()),
       (3, 'Écran', 'Moniteur 4K de 27 pouces pour un affichage haute résolution.', 15.00, 'GOOD_STATE', 1, true, NOW(),
        NOW()),
       (4, 'Clavier', 'Clavier mécanique pour un confort de frappe.', 5.00, 'GOOD_STATE', 1, true, NOW(), NOW()),
       (5, 'Souris', 'Souris sans fil pour une navigation facile.', 4.00, 'GOOD_STATE', 1, true, NOW(), NOW()),
       (6, 'Routeur', 'Routeur haut débit pour la connectivité Internet.', 10.00, 'GOOD_STATE', 1, true, NOW(), NOW()),
       (7, 'Commutateur réseau', 'Commutateur pour connecter plusieurs appareils.', 12.00, 'GOOD_STATE', 1, true, NOW(),
        NOW()),
       (8, 'Disque dur', 'Disque dur externe pour le stockage de données.', 20.00, 'GOOD_STATE', 1, true, NOW(), NOW()),
       (9, 'SSD', 'Disque SSD pour un accès plus rapide aux données.', 18.00, 'GOOD_STATE', 1, true, NOW(), NOW()),
       (10, 'Alimentation', 'Alimentation fiable pour ordinateurs.', 15.00, 'GOOD_STATE', 1, true, NOW(), NOW()),
       (11, 'Jeu de clés', 'Jeu de clés pour les réparations mécaniques.', 10.00, 'GOOD_STATE', 2, true, NOW(), NOW()),
       (12, 'Jeu de douilles', 'Jeu de douilles pour différentes tailles d’écrous et de boulons.', 12.00, 'GOOD_STATE',
        2, true, NOW(), NOW()),
       (13, 'Clé dynamométrique', 'Clé dynamométrique de précision pour un serrage exact.', 20.00, 'GOOD_STATE', 2,
        true, NOW(), NOW()),
       (14, 'Perceuse pneumatique', 'Perceuse à air comprimé pour travaux intensifs.', 30.00, 'GOOD_STATE', 2, true,
        NOW(), NOW()),
       (15, 'Cric de voiture', 'Cric hydraulique pour soulever des véhicules.', 25.00, 'GOOD_STATE', 2, true, NOW(),
        NOW()),
       (16, 'Coupe-verre', 'Outil pour couper les feuilles de verre.', 8.00, 'GOOD_STATE', 3, true, NOW(), NOW()),
       (17, 'Ventouse', 'Ventouse pour manipuler le verre en toute sécurité.', 5.00, 'GOOD_STATE', 3, true, NOW(),
        NOW()),
       (18, 'Lunettes de sécurité', 'Lunettes de protection pour les travaux sur verre.', 4.00, 'GOOD_STATE', 3, true,
        NOW(), NOW()),
       (19, 'Nettoyant pour verre', 'Nettoyant spécialisé pour surfaces vitrées.', 3.00, 'GOOD_STATE', 3, true, NOW(),
        NOW()),
       (20, 'Couteau à mastic', 'Outil pour appliquer le mastic lors des réparations de verre.', 6.00, 'GOOD_STATE', 3,
        true, NOW(), NOW()),
       (21, 'Support pour ordinateur portable', 'Support ergonomique pour ordinateurs portables.', 10.00, 'GOOD_STATE',
        1, true, NOW(), NOW()),
       (22, 'Hub USB', 'Hub USB pour connecter plusieurs appareils.', 8.00, 'GOOD_STATE', 1, true, NOW(), NOW()),
       (23, 'Câble HDMI', 'Câble HDMI pour interface multimédia haute définition.', 2.50, 'GOOD_STATE', 1, true, NOW(),
        NOW()),
       (24, 'Câble Ethernet', 'Câble réseau pour connexions filaires.', 3.00, 'GOOD_STATE', 1, true, NOW(), NOW()),
       (25, 'Webcam', 'Webcam HD pour visioconférences.', 15.00, 'GOOD_STATE', 1, true, NOW(), NOW()),
       (26, 'Microphone', 'Microphone USB pour un enregistrement audio clair.', 12.00, 'GOOD_STATE', 1, true, NOW(),
        NOW()),
       (27, 'Carte graphique', 'Carte graphique haute performance pour le jeu.', 100.00, 'GOOD_STATE', 1, true, NOW(),
        NOW()),
       (28, 'Carte mère', 'Carte mère pour assemblage de PC personnalisés.', 80.00, 'GOOD_STATE', 1, true, NOW(),
        NOW()),
       (29, 'RAM', 'Module de RAM 16 Go pour de meilleures performances.', 40.00, 'GOOD_STATE', 1, true, NOW(), NOW()),
       (30, 'Ventilateur de refroidissement', 'Ventilateur pour le refroidissement des systèmes informatiques.', 10.00,
        'GOOD_STATE', 1, true, NOW(), NOW()),
       (31, 'Jeu de forets', 'Jeu de forets pour divers matériaux.', 15.00, 'GOOD_STATE', 2, true, NOW(), NOW()),
       (32, 'Jeu de vis', 'Assortiment de vis pour applications mécaniques.', 5.00, 'GOOD_STATE', 2, true, NOW(),
        NOW()),
       (33, 'Mètre ruban', 'Mètre ruban flexible pour des mesures précises.', 3.50, 'GOOD_STATE', 2, true, NOW(),
        NOW()),
       (34, 'Gants de sécurité', 'Gants de protection pour travaux mécaniques.', 4.00, 'GOOD_STATE', 2, true, NOW(),
        NOW()),
       (35, 'Kit de réparation de verre', 'Kit complet pour réparer les surfaces vitrées.', 20.00, 'GOOD_STATE', 3,
        true, NOW(), NOW()),
       (36, 'Mastic pour fenêtres', 'Mastic pour l’installation et l’étanchéité des vitres.', 7.00, 'GOOD_STATE', 3,
        true, NOW(), NOW()),
       (37, 'Polisseuse pour verre', 'Outil pour polir les surfaces vitrées.', 15.00, 'GOOD_STATE', 3, true, NOW(),
        NOW()),
       (38, 'Film de sécurité pour verre', 'Film protecteur pour surfaces vitrées.', 10.00, 'GOOD_STATE', 3, true,
        NOW(), NOW()),
       (39, 'Multimètre numérique', 'Outil pour mesurer des valeurs électriques.', 25.00, 'GOOD_STATE', 1, true, NOW(),
        NOW()),
       (40, 'Fer à souder', 'Outil pour souder des composants électroniques.', 20.00, 'GOOD_STATE', 1, true, NOW(),
        NOW()),
       (41, 'Pistolet à air chaud', 'Outil pour appliquer de la chaleur sur divers matériaux.', 30.00, 'GOOD_STATE', 1,
        true, NOW(), NOW()),
       (42, 'Pince à dénuder', 'Outil pour enlever l’isolation des fils électriques.', 5.00, 'GOOD_STATE', 1, true,
        NOW(), NOW()),
       (43, 'Carte de circuit imprimé', 'Carte de circuits personnalisée pour projets électroniques.', 50.00,
        'GOOD_STATE', 1, true, NOW(), NOW()),
       (44, 'Perceuse électrique', 'Perceuse sans fil pour divers travaux.', 40.00, 'GOOD_STATE', 2, true, NOW(),
        NOW()),
       (45, 'Compresseur d’air', 'Compresseur d’air portable pour outils pneumatiques.', 60.00, 'GOOD_STATE', 2, true,
        NOW(), NOW()),
       (46, 'Vitrine en verre', 'Vitrine pour exposer des objets en verre.', 100.00, 'GOOD_STATE', 3, true, NOW(),
        NOW()),
       (47, 'Cadre de fenêtre', 'Cadre pour l’installation de fenêtres vitrées.', 30.00, 'GOOD_STATE', 3, true, NOW(),
        NOW()),
       (48, 'Panneau en verre', 'Panneau de verre trempé pour les installations.', 50.00, 'GOOD_STATE', 3, true, NOW(),
        NOW()),
       (49, 'Mastic silicone', 'Mastic pour l’étanchéité des installations en verre.', 8.00, 'GOOD_STATE', 3, true,
        NOW(), NOW()),
       (50, 'Colle de réparation pour verre', 'Colle spéciale pour réparer les surfaces en verre.', 12.00, 'GOOD_STATE',
        3, true, NOW(), NOW()),
       (51, 'Perceuse sans fil', 'Perceuse électrique portable avec batterie rechargeable', 10.50, 'GOOD_STATE', 1,
        TRUE, NOW(), NOW())
        ,
       (52, 'Scie circulaire', 'Scie à moteur pour découper des matériaux épais', 15.00, 'GOOD_STATE', 1, TRUE, NOW(),
        NOW()),
       (53, 'Pelle de jardin', 'Outil pour creuser et déplacer la terre', 5.00, 'GOOD_STATE', 2, TRUE, NOW(), NOW()),
       (54, 'Marteau', 'Outil pour enfoncer des clous ou d’autres objets', 3.00, 'GOOD_STATE', 1, TRUE, NOW(), NOW()),
       (55, 'Râteau de jardin', 'Outil de jardinage pour niveler la terre ou ramasser les feuilles', 4.00, 'GOOD_STATE',
        2, TRUE, NOW(), NOW()),
       (56, 'Tournevis', 'Outil pour visser et dévisser des vis', 2.50, 'GOOD_STATE', 1, TRUE, NOW(), NOW()),
       (57, 'Mètre ruban', 'Outil de mesure flexible pour mesurer des distances', 1.50, 'GOOD_STATE', 1, TRUE, NOW(),
        NOW()),
       (58, 'Scie à main', 'Scie manuelle pour couper du bois ou des matériaux similaires', 6.00, 'GOOD_STATE', 1, TRUE,
        NOW(), NOW()),
       (59, 'Ciseaux de jardin', 'Ciseaux pour tailler les plantes et les arbustes', 4.50, 'GOOD_STATE', 2, TRUE, NOW(),
        NOW()),
       (60, 'Tondeuse à gazon', 'Machine pour tondre l’herbe du jardin', 12.00, 'GOOD_STATE', 2, TRUE, NOW(), NOW()),
       (61, 'Perceuse à percussion', 'Perceuse pour percer des trous dans des matériaux durs', 18.00, 'GOOD_STATE', 1,
        TRUE, NOW(), NOW()),
       (62, 'Pistolet à peinture', 'Pistolet utilisé pour appliquer de la peinture uniformément', 20.00, 'GOOD_STATE',
        1, TRUE, NOW(), NOW()),
       (63, 'Brouette', 'Outil pour transporter du matériel ou de la terre', 7.50, 'GOOD_STATE', 2, TRUE, NOW(), NOW()),
       (64, 'Lance d’arrosage', 'Lance pour arroser les plantes de manière uniforme', 3.00, 'GOOD_STATE', 2, TRUE,
        NOW(), NOW()),
       (65, 'Clé à molette', 'Outil pour serrer ou desserrer des écrous et vis', 5.00, 'GOOD_STATE', 1, TRUE, NOW(),
        NOW()),
       (66, 'Détecteur de métaux', 'Outil électronique pour détecter des objets métalliques', 25.00, 'GOOD_STATE', 1,
        TRUE, NOW(), NOW()),
       (67, 'Échelle', 'Échelle télescopique pour atteindre des hauteurs élevées', 8.00, 'GOOD_STATE', 1, TRUE, NOW(),
        NOW()),
       (68, 'Compresseur d’air', 'Appareil pour générer de l’air comprimé à utiliser avec divers outils', 15.00,
        'GOOD_STATE', 1, TRUE, NOW(), NOW()),
       (69, 'Générateur électrique', 'Générateur portable pour produire de l’électricité', 30.00, 'GOOD_STATE', 1, TRUE,
        NOW(), NOW()),
       (70, 'Couteau multifonction', 'Outil compact avec différentes fonctions pour les réparations', 4.00,
        'GOOD_STATE', 1, TRUE, NOW(), NOW()),
       (71, 'Clé à pipe', 'Clé pour visser ou dévisser des écrous', 6.00, 'GOOD_STATE', 1, TRUE, NOW(), NOW()),
       (72, 'Coffre à outils', 'Coffre contenant divers outils pour le bricolage', 8.50, 'GOOD_STATE', 1, TRUE, NOW(),
        NOW()),
       (73, 'Pelle à neige', 'Pelle pour déneiger les allées et les routes', 3.00, 'GOOD_STATE', 2, TRUE, NOW(), NOW()),
       (74, 'Pompe à eau', 'Appareil pour pomper l’eau dans un espace fermé ou pour l’arrosage', 12.00, 'GOOD_STATE', 2,
        TRUE, NOW(), NOW()),
       (75, 'Gants de protection', 'Gants utilisés pour protéger les mains lors de travaux manuels', 2.00, 'GOOD_STATE',
        1, TRUE, NOW(), NOW()),
       (76, 'Mèche à bois', 'Outil utilisé pour percer du bois', 1.50, 'GOOD_STATE', 1, TRUE, NOW(), NOW()),
       (77, 'Pied de biche', 'Outil utilisé pour lever des objets lourds ou retirer des clous', 4.50, 'GOOD_STATE', 1,
        TRUE, NOW(), NOW()),
       (78, 'Bande de masquage', 'Ruban adhésif pour protéger les surfaces lors de la peinture', 2.00, 'GOOD_STATE', 1,
        TRUE, NOW(), NOW()),
       (79, 'Tondeuse de haie', 'Outil pour tailler et maintenir les haies de jardin', 10.00, 'GOOD_STATE', 2, TRUE,
        NOW(), NOW()),
       (80, 'Scie sabre', 'Scie à mouvement pendulaire pour couper des matériaux épais', 18.50, 'GOOD_STATE', 1, TRUE,
        NOW(), NOW()),
       (81, 'Pistolet thermique', 'Outil utilisé pour décoller des matériaux ou sécher rapidement', 15.00, 'GOOD_STATE',
        1, TRUE, NOW(), NOW()),
       (82, 'Tronçonneuse', 'Outil pour couper du bois ou des branches épaisses', 20.00, 'GOOD_STATE', 2, TRUE, NOW(),
        NOW()),
       (83, 'Chiffon de nettoyage', 'Chiffon pour essuyer et nettoyer les surfaces', 1.00, 'GOOD_STATE', 1, TRUE, NOW(),
        NOW()),
       (84, 'Clé à douilles', 'Clé utilisée avec des douilles pour serrer ou desserrer des écrous et vis', 5.50,
        'GOOD_STATE', 1, TRUE, NOW(), NOW()),
       (85, 'Aspirateur industriel', 'Aspirateur puissant pour nettoyer les chantiers', 25.00, 'GOOD_STATE', 1, TRUE,
        NOW(), NOW()),
       (86, 'Masque de protection', 'Masque pour se protéger des poussières et gaz', 3.50, 'GOOD_STATE', 1, TRUE, NOW(),
        NOW()),
       (87, 'Visseuse', 'Outil pour visser et dévisser rapidement', 7.00, 'GOOD_STATE', 1, TRUE, NOW(), NOW()),
       (88, 'Grille de barbecue', 'Grille utilisée pour faire cuire des aliments sur un barbecue', 4.00, 'GOOD_STATE',
        2, TRUE, NOW(), NOW()),
       (89, 'Crochet de levage', 'Crochet pour soulever des charges lourdes', 6.50, 'GOOD_STATE', 1, TRUE, NOW(),
        NOW()),
       (90, 'Boîte à outils', 'Caisse avec divers outils de travail', 10.00, 'GOOD_STATE', 1, TRUE, NOW(), NOW()),
       (91, 'Clé à chocs', 'Clé électrique utilisée pour visser et dévisser rapidement', 22.00, 'GOOD_STATE', 1, TRUE,
        NOW(), NOW()),
       (92, 'Lampe de chantier', 'Lampe puissante pour éclairer les zones de travail', 8.00, 'GOOD_STATE', 1, TRUE,
        NOW(), NOW()),
       (93, 'Brouette à pneus', 'Brouette avec des pneus pour transporter des charges lourdes', 9.00, 'GOOD_STATE', 2,
        TRUE, NOW(), NOW()),
       (94, 'Échelle d’extension', 'Échelle extensible pour atteindre de plus grandes hauteurs', 12.00, 'GOOD_STATE', 1,
        TRUE, NOW(), NOW()),
       (95, 'Pince multiprise', 'Pince qui peut saisir une grande variété de matériaux', 5.50, 'GOOD_STATE', 1, TRUE,
        NOW(), NOW()),
       (96, 'Perforateur', 'Perforateur électrique pour percer les matériaux durs', 20.00, 'GOOD_STATE', 1, TRUE, NOW(),
        NOW());