CREATE TABLE materials
(
    id                   bigint                 NOT NULL,
    name_material        character varying(255) NOT NULL,
    description_material text,
    price_hour_material  numeric(7, 2)          NOT NULL,
    state_material       character varying(255),
    category_id          bigint,
    is_available         boolean,
    created_at           timestamp(6) without time zone NOT NULL,
    updated_at           timestamp(6) without time zone,
    CONSTRAINT materials_state_material_check CHECK (((state_material)::text = ANY ((ARRAY['GOOD_STATE':: character varying, 'BAD_STATE':: character varying, 'DAMAGED_STATE':: character varying])::text[])
) )
);

ALTER TABLE materials
ALTER
COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME materials_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

ALTER TABLE materials
    ADD CONSTRAINT materials_pkey PRIMARY KEY (id);

ALTER TABLE materials
    ADD CONSTRAINT material_to_category
        FOREIGN KEY (category_id)
            REFERENCES categories (id);

ALTER TABLE materials
    ADD CONSTRAINT upDel_material
        FOREIGN KEY (category_id)
            REFERENCES materials (id)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;