INSERT INTO favour (id, name_favor, description_favor, price_hour_favor, created_at, updated_at, category_id,
                    is_available)
VALUES (1, 'Dépannage informatique', 'Assistance pour résoudre les problèmes informatiques.', 30.00, NOW(), NOW(), 1,
        true),
       (2, 'Réparation de plomberie', 'Services de réparation de plomberie pour fuites et installations.', 40.00, NOW(),
        NOW(), 2, true),
       (3, 'Peinture intérieure', 'Peinture des murs et plafonds intérieurs.', 25.00, NOW(), NOW(), 3, true),
       (4, 'Peinture extérieure', 'Peinture des façades et extérieurs.', 35.00, NOW(), NOW(), 3, true),
       (5, 'Surveillance de sécurité', 'Services de surveillance pour la sécurité des locaux.', 50.00, NOW(), NOW(), 4,
        true),
       (6, 'Assistance technique', 'Aide technique pour divers appareils électroniques.', 20.00, NOW(), NOW(), 1, true),
       (7, 'Réparation de vitres', 'Remplacement et réparation de vitres cassées.', 45.00, NOW(), NOW(), 2, true),
       (8, 'Installation de logiciels', 'Installation et configuration de logiciels sur ordinateurs.', 15.00, NOW(),
        NOW(), 1, true),
       (9, 'Configuration de réseau', 'Mise en place et configuration de réseaux informatiques.', 30.00, NOW(), NOW(),
        1, true),
       (10, 'Peinture de meubles', 'Peinture et restauration de meubles en bois.', 20.00, NOW(), NOW(), 3, true),
       (11, 'Dépannage électroménager', 'Réparation d’appareils électroménagers.', 35.00, NOW(), NOW(), 2, true),
       (12, 'Nettoyage de vitres', 'Service de nettoyage de vitres pour maisons et bureaux.', 25.00, NOW(), NOW(), 2,
        true),
       (13, 'Installation de rideaux', 'Installation de rideaux et stores.', 15.00, NOW(), NOW(), 3, true),
       (14, 'Surveillance à distance', 'Surveillance vidéo à distance pour la sécurité.', 60.00, NOW(), NOW(), 4, true),
       (15, 'Réparation de meubles', 'Réparation et restauration de meubles endommagés.', 30.00, NOW(), NOW(), 3, true),
       (16, 'Dépannage de voiture', 'Assistance pour les pannes de voiture.', 50.00, NOW(), NOW(), 2, true),
       (17, 'Peinture de façade', 'Peinture extérieure des façades de bâtiments.', 40.00, NOW(), NOW(), 3, true),
       (18, 'Installation de systèmes de sécurité', 'Installation de systèmes de sécurité pour maisons.', 70.00, NOW(),
        NOW(), 4, true),
       (19, 'Réparation de plomberie d’urgence', 'Services de plomberie d’urgence.', 50.00, NOW(), NOW(), 2, true),
       (20, 'Dépannage de réseau', 'Assistance pour les problèmes de réseau informatique.', 30.00, NOW(), NOW(), 1,
        true),
       (21, 'Peinture de chambre', 'Peinture des chambres à coucher.', 25.00, NOW(), NOW(), 3, true),
       (22, 'Réparation de toiture', 'Services de réparation de toitures.', 60.00, NOW(), NOW(), 2, true),
       (23, 'Installation de fenêtres', 'Installation de nouvelles fenêtres.', 45.00, NOW(), NOW(), 2, true),
       (24, 'Surveillance de chantier', 'Surveillance de chantiers de construction.', 55.00, NOW(), NOW(), 4, true),
       (25, 'Dépannage de systèmes audio', 'Assistance pour les systèmes audio.', 20.00, NOW(), NOW(), 1, true),
       (26, 'Peinture de clôture', 'Peinture des clôtures extérieures.', 30.00, NOW(), NOW(), 3, true),
       (27, 'Réparation de carrelage', 'Réparation et remplacement de carrelage.', 40.00, NOW(), NOW(), 2, true),
       (28, 'Installation de luminaires', 'Installation de luminaires et éclairage.', 20.00, NOW(), NOW(), 3, true),
       (29, 'Dépannage de chauffage', 'Assistance pour les systèmes de chauffage.', 50.00, NOW(), NOW(), 2, true),
       (30, 'Peinture de portes', 'Peinture et finition de portes intérieures.', 25.00, NOW(), NOW(), 3, true),
       (31, 'Réparation de fenêtres', 'Réparation et entretien de fenêtres.', 35.00, NOW(), NOW(), 2, true),
       (32, 'Installation de systèmes d’alarme', 'Installation de systèmes d’alarme pour la sécurité.', 70.00, NOW(),
        NOW(), 4, true),
       (33, 'Dépannage de climatisation', 'Assistance pour les systèmes de climatisation.', 50.00, NOW(), NOW(), 2,
        true),
       (34, 'Peinture de sous-sol', 'Peinture des sous-sols et espaces de rangement.', 30.00, NOW(), NOW(), 3, true),
       (35, 'Réparation de murs', 'Réparation de murs endommagés.', 40.00, NOW(), NOW(), 2, true),
       (36, 'Installation de panneaux solaires', 'Installation de systèmes de panneaux solaires.', 80.00, NOW(), NOW(),
        4, true),
       (37, 'Dépannage de systèmes de sécurité', 'Assistance pour les systèmes de sécurité.', 30.00, NOW(), NOW(), 1,
        true),
       (38, 'Peinture de garage', 'Peinture des garages et abris de jardin.', 25.00, NOW(), NOW(), 3, true),
       (39, 'Réparation de clôtures', 'Réparation et entretien de clôtures.', 35.00, NOW(), NOW(), 2, true),
       (40, 'Surveillance de propriété', 'Surveillance de propriétés privées.', 60.00, NOW(), NOW(), 4, true),
       (41, 'Dépannage de systèmes de son', 'Assistance pour les systèmes de son.', 20.00, NOW(), NOW(), 1, true),
       (42, 'Peinture de mobilier de jardin', 'Peinture et entretien de mobilier de jardin.', 30.00, NOW(), NOW(), 3,
        true),
       (43, 'Réparation de systèmes de ventilation', 'Assistance pour les systèmes de ventilation.', 50.00, NOW(),
        NOW(), 2, true),
       (44, 'Installation de rideaux de douche', 'Installation de rideaux de douche et accessoires.', 15.00, NOW(),
        NOW(), 3, true),
       (45, 'Dépannage de systèmes de plomberie', 'Assistance pour les systèmes de plomberie.', 40.00, NOW(), NOW(), 2,
        true),
       (46, 'Peinture de balcons', 'Peinture des balcons et terrasses.', 35.00, NOW(), NOW(), 3, true),
       (47, 'Réparation de systèmes de climatisation', 'Assistance pour les systèmes de climatisation.', 50.00, NOW(),
        NOW(), 2, true),
       (48, 'Surveillance de locaux commerciaux', 'Surveillance de locaux commerciaux.', 70.00, NOW(), NOW(), 4, true),
       (49, 'Dépannage de systèmes de chauffage', 'Assistance pour les systèmes de chauffage.', 30.00, NOW(), NOW(), 1,
        true),
       (50, 'Peinture de murs extérieurs', 'Peinture des murs extérieurs des bâtiments.', 40.00, NOW(), NOW(), 3, true),
       (51, 'Jardinage - Tonte de pelouse', 'Tonte régulière ou ponctuelle de votre pelouse', 15.00, now(), now(), 2,
        TRUE),
       (52, 'Jardinage - Taille de haies', 'Taille et entretien des haies', 18.00, now(), now(), 2, TRUE),
       (53, 'Jardinage - Désherbage', 'Enlèvement manuel ou chimique des mauvaises herbes', 12.00, now(), now(), 2,
        TRUE),
       (54, 'Jardinage - Arrosage', 'Arrosage de plantes et potagers', 10.00, now(), now(), 2, TRUE),
       (55, 'Construction - Montage de meubles', 'Assemblage et installation de meubles en kit', 20.00, now(), now(), 1,
        TRUE),
       (56, 'Construction - Peinture murale', 'Peinture intérieure et extérieure', 25.00, now(), now(), 1, TRUE),
       (57, 'Construction - Petite plomberie', 'Réparation de fuites et installation simple', 30.00, now(), now(), 1,
        TRUE),
       (58, 'Construction - Électricité basique', 'Installation d’appareils et petites réparations électriques', 35.00,
        now(), now(), 1, TRUE),
       (59, 'Déménagement', 'Aide au chargement, déchargement et transport', 22.00, now(), now(), 3, TRUE),
       (60, 'Nettoyage', 'Nettoyage de maison, appartement, bureaux', 15.00, now(), now(), 4, TRUE),
       (61, 'Cours particuliers', 'Soutien scolaire et aide aux devoirs', 25.00, now(), now(), 5, TRUE),
       (62, 'Garde d’enfants', 'Garde ponctuelle ou régulière', 18.00, now(), now(), 6, TRUE),
       (63, 'Cours de langue', 'Cours particuliers pour apprendre une langue', 20.00, now(), now(), 5, TRUE),
       (64, 'Aide informatique', 'Dépannage et conseils informatique à domicile', 30.00, now(), now(), 7, TRUE),
       (65, 'Livraison', 'Livraison de courses ou colis', 12.00, now(), now(), 8, TRUE),
       (66, 'Assistance administrative', 'Aide dans la rédaction de documents et démarches', 20.00, now(), now(), 9,
        TRUE),
       (67, 'Soins aux animaux', 'Promenade et garde d’animaux', 15.00, now(), now(), 10, TRUE),
       (68, 'Réparation vélo', 'Petites réparations et entretien', 18.00, now(), now(), 11, TRUE),
       (69, 'Cuisine à domicile', 'Préparation de repas pour particuliers', 20.00, now(), now(), 12, TRUE),
       (70, 'Soutien moral', 'Écoute et soutien psychologique', 15.00, now(), now(), 13, TRUE),
       (71, 'Aide aux personnes âgées', 'Assistance à domicile pour les tâches quotidiennes', 20.00, now(), now(), 14,
        TRUE),
       (72, 'Coaching sportif', 'Séances personnalisées de sport et remise en forme', 30.00, now(), now(), 15, TRUE),
       (73, 'Photographie', 'Shooting photo pour événements et particuliers', 40.00, now(), now(), 16, TRUE),
       (74, 'Jardinage - Plantation', 'Plantation de fleurs, arbustes et arbres', 18.00, now(), now(), 2, TRUE),
       (75, 'Construction - Réparation murale', 'Réparation de fissures et petits travaux', 25.00, now(), now(), 1,
        TRUE),
       (76, 'Nettoyage - Vitres', 'Nettoyage professionnel de fenêtres', 15.00, now(), now(), 4, TRUE),
       (77, 'Aide au bricolage', 'Conseils et petits travaux de bricolage', 20.00, now(), now(), 1, TRUE),
       (78, 'Déménagement - Emballage', 'Aide pour emballer et protéger vos biens', 18.00, now(), now(), 3, TRUE),
       (79, 'Cours de musique', 'Cours pour guitare, piano et autres instruments', 25.00, now(), now(), 5, TRUE),
       (80, 'Entretien piscine', 'Nettoyage et maintenance de piscine', 30.00, now(), now(), 17, TRUE),
       (81, 'Création site web', 'Développement de sites vitrines simples', 40.00, now(), now(), 7, TRUE),
       (82, 'Gardiennage maison', 'Surveillance ponctuelle de résidence', 18.00, now(), now(), 18, TRUE),
       (83, 'Peinture décorative', 'Fresques, trompe-l’oeil et peintures artistiques', 30.00, now(), now(), 1, TRUE),
       (84, 'Livraison courses', 'Courses livrées à domicile rapidement', 12.00, now(), now(), 8, TRUE),
       (85, 'Montage informatique', 'Installation de matériel informatique et logiciels', 25.00, now(), now(), 7, TRUE),
       (86, 'Soutien scolaire - Maths', 'Aide en mathématiques pour tous niveaux', 25.00, now(), now(), 5, TRUE),
       (87, 'Réparation électroménager', 'Petites réparations appareils électroménagers', 30.00, now(), now(), 1, TRUE),
       (88, 'Coaching nutritionnel', 'Conseils personnalisés pour une alimentation saine', 35.00, now(), now(), 15,
        TRUE),
       (89, 'Transport animaux', 'Transport sécurisé pour vos animaux', 20.00, now(), now(), 10, TRUE),
       (90, 'Photographie événementielle', 'Couverture photo pour événements', 50.00, now(), now(), 16, TRUE),
       (91, 'Soutien scolaire - Français', 'Aide en français et littérature', 25.00, now(), now(), 5, TRUE),
       (92, 'Réparation smartphones', 'Dépannage et réparation de téléphones mobiles', 30.00, now(), now(), 7, TRUE),
       (93, 'Déménagement - Nettoyage', 'Nettoyage complet après déménagement', 20.00, now(), now(), 4, TRUE),
       (94, 'Cours de dessin', 'Initiation et perfectionnement en dessin', 20.00, now(), now(), 5, TRUE),
       (95, 'Aide informatique - Formation', 'Formations personnalisées à l’outil informatique', 30.00, now(), now(), 7,
        TRUE),
       (96, 'Petits travaux électriques', 'Installation et réparation simples', 30.00, now(), now(), 1, TRUE),
       (97, 'Couture et retouches', 'Retouches de vêtements à domicile', 20.00, now(), now(), 19, TRUE),
       (98, 'Assistance administrative', 'Aide dans les démarches administratives', 20.00, now(), now(), 9, TRUE),
       (99, 'Livraison colis', 'Service de livraison rapide et sécurisé', 12.00, now(), now(), 8, TRUE),
       (100, 'Garde animaux à domicile', 'Soins et présence pour vos animaux', 15.00, now(), now(), 10, TRUE);