INSERT INTO favour (id, name_favor, description_favor, price_hour_favor, created_at, updated_at, category_id,
                    is_available)
VALUES (1, 'Réparation d’ordinateur', 'Réparation de matériel informatique (ordinateurs de bureau, portables, etc.)',
        40, NOW(), NOW(), 1, true),
       (2, 'Installation de systèmes de sécurité',
        'Installation de caméras, alarmes, et autres systèmes de sécurité pour la maison ou entreprise', 60, NOW(),
        NOW(), 5, true),
       (3, 'Montage de meubles', 'Assemblage de meubles achetés en kit (Ikea, etc.)', 30, NOW(), NOW(), 8, true),
       (4, 'Tonte de pelouse', 'Tonte régulière de pelouse et entretien de jardin', 25, NOW(), NOW(), 6, true),
       (5, 'Peinture intérieure', 'Peinture de murs et plafonds dans les espaces intérieurs', 50, NOW(), NOW(), 7,
        true),
       (6, 'Soudure métallique', 'Soudure pour projets métalliques tels que structures ou réparations', 55, NOW(),
        NOW(), 29, true),
       (7, 'Plomberie générale', 'Réparation, installation et entretien des systèmes de plomberie', 45, NOW(), NOW(),
        10, true),
       (8, 'Réparation de verre', 'Réparation de fenêtres et autres objets en verre', 50, NOW(), NOW(), 3, true),
       (9, 'Vente et installation de panneaux solaires',
        'Installation de systèmes solaires pour l\''énergie domestique ou commerciale', 75, NOW(), NOW(), 12, true),
       (10, 'Maintenance automobile', 'Réparation et entretien de véhicules (moteur, freins, etc.)', 60, NOW(), NOW(),
        15, true),
       (11, 'Électricien à domicile', 'Installation ou réparation de câblage électrique, prises, interrupteurs', 55,
        NOW(), NOW(), 4, true),
       (12, 'Dépannage informatique', 'Réparation de tous types de pannes informatiques (PC, Mac, etc.)', 40, NOW(),
        NOW(), 1, true),
       (13, 'Nettoyage industriel', 'Nettoyage de bureaux, entrepôts et espaces industriels', 35, NOW(), NOW(), 27,
        true),
       (14, 'Installation de climatisation', 'Installation de systèmes de climatisation dans les bâtiments', 70, NOW(),
        NOW(), 13, true),
       (15, 'Pose de carrelage', 'Pose de carrelage dans les cuisines, salles de bain, etc.', 50, NOW(), NOW(), 14,
        true),
       (16, 'Création de site web', 'Conception et développement de sites web professionnels', 80, NOW(), NOW(), 49,
        true),
       (17, 'Design de logos', 'Création de logos et d\''identités visuelles pour entreprises', 60, NOW(), NOW(), 49,
        true),
       (18, 'Création de contenu vidéo', 'Production de vidéos pour entreprises ou événements', 90, NOW(), NOW(), 23,
        true),
       (19, 'SEO et optimisation de site', 'Amélioration de la visibilité d\''un site web sur les moteurs de recherche',
        70, NOW(), NOW(), 52, true),
       (20, 'Rédaction d’articles de blog', 'Rédaction et optimisation d\''articles de blog pour sites web', 45, NOW(),
        NOW(), 52, true),
       (21, 'Conseil en gestion de projet',
        'Accompagnement pour la gestion et la planification de projets professionnels', 100, NOW(), NOW(), 43, true),
       (22, 'Assistance administrative',
        'Aide pour la gestion de tâches administratives diverses (emails, agendas, etc.)', 35, NOW(), NOW(), 20, true),
       (23, 'Réparation de téléphone portable', 'Réparation de smartphones (écran, batterie, etc.)', 40, NOW(), NOW(),
        1, true),
       (24, 'Service de traduction', 'Traduction de documents dans plusieurs langues', 60, NOW(), NOW(), 47, true),
       (25, 'Coaching personnel', 'Séances de coaching pour améliorer le bien-être personnel', 85, NOW(), NOW(), 60,
        true),
       (26, 'Formation en gestion du temps', 'Cours et conseils pour mieux gérer son temps personnel et professionnel',
        55, NOW(), NOW(), 62, true),
       (27, 'Cours particuliers en mathématiques', 'Sessions de tutorat en mathématiques pour élèves de tous niveaux',
        50, NOW(), NOW(), 64, true),
       (28, 'Soutien scolaire', 'Accompagnement scolaire personnalisé pour les élèves de primaire et secondaire', 30,
        NOW(), NOW(), 64, true),
       (29, 'Photographie événementielle', 'Photographie d\''événements tels que mariages, anniversaires, conférences',
        150, NOW(), NOW(), 49, true),
       (30, 'Aménagement de bureau',
        'Création et aménagement d\''espaces de travail (bureau à domicile, espace entreprise)', 70, NOW(), NOW(), 21,
        true),
       (31, 'Création d’applications mobiles', 'Développement d\''applications mobiles pour iOS et Android', 100, NOW(),
        NOW(), 56, true),
       (32, 'Dépannage de voiture', 'Assistance en cas de panne automobile sur la route', 75, NOW(), NOW(), 15, true),
       (33, 'Création de stratégie marketing', 'Développement de stratégies marketing pour entreprises et start-ups',
        90, NOW(), NOW(), 52, true),
       (34, 'Audit de sécurité informatique', 'Évaluation de la sécurité d\''un réseau informatique et recommandations',
        110, NOW(), NOW(), 4, true),
       (35, 'Gestion des réseaux sociaux', 'Gestion des comptes de réseaux sociaux pour entreprises', 60, NOW(), NOW(),
        49, true),
       (36, 'Réparation de toiture', 'Réparation et entretien de toitures pour maisons et bâtiments', 70, NOW(), NOW(),
        14, true),
       (37, 'Rénovation de cuisine', 'Rénovation complète ou partielle de cuisines', 85, NOW(), NOW(), 14, true),
       (38, 'Réparation de canalisations', 'Réparation et maintenance des canalisations et des tuyaux', 50, NOW(),
        NOW(), 10, true),
       (39, 'Nettoyage après sinistre', 'Nettoyage et désinfection après un sinistre ou dégât des eaux', 60, NOW(),
        NOW(), 27, true),
       (40, 'Aménagement de jardin', 'Design et aménagement paysager pour jardins et espaces extérieurs', 75, NOW(),
        NOW(), 6, true),
       (41, 'Coaching de vie', 'Séances de coaching pour un développement personnel et professionnel', 100, NOW(),
        NOW(), 60, true),
       (42, 'Installation de systèmes d’irrigation',
        'Installation et maintenance de systèmes d’irrigation pour jardins', 50, NOW(), NOW(), 6, true),
       (43, 'Débouchage de canalisations', 'Service de débouchage pour canalisations obstruées', 40, NOW(), NOW(), 10,
        true),
       (44, 'Service de baby-sitting', 'Garde d\''enfants à domicile pour des heures ponctuelles ou régulières', 20,
        NOW(), NOW(), 17, true),
       (45, 'Événementiel - Organisation de mariage',
        'Organisation complète d\''un mariage, y compris décoration et logistique', 200, NOW(), NOW(), 42, true),
       (46, 'Gestion des finances personnelles', 'Conseils et gestion des finances personnelles pour particuliers', 90,
        NOW(), NOW(), 46, true),
       (47, 'Conseil juridique', 'Assistance et conseils juridiques pour les entreprises et particuliers', 120, NOW(),
        NOW(), 45, true),
       (48, 'Conseil en marketing digital', 'Stratégies de marketing digital et gestion de campagnes en ligne', 100,
        NOW(), NOW(), 52, true),
       (49, 'Consultation en image de marque',
        'Aide pour la création et gestion de l\''image de marque de votre entreprise', 110, NOW(), NOW(), 49, true),
       (50, 'Réparation d’appareils électroménagers',
        'Réparation de petits et grands électroménagers (réfrigérateurs, machines à laver, etc.)', 55, NOW(), NOW(), 11,
        true),
       (51, 'Création de visuels publicitaires',
        'Conception de visuels pour des campagnes publicitaires (affiches, bannières, flyers)', 80, NOW(), NOW(), 49,
        true),
       (52, 'Entretien de piscine', 'Nettoyage, traitement de l\''eau et entretien régulier des piscines', 60, NOW(),
        NOW(), 6, true),
       (53, 'Livraison de courses', 'Livraison de courses à domicile ou au bureau', 20, NOW(), NOW(), 22, true),
       (54, 'Formation en Excel',
        'Formation à l\''utilisation avancée d\''Excel pour les professionnels et particuliers', 50, NOW(), NOW(), 52,
        true),
       (55, 'Déménagement', 'Service de déménagement (emballage, transport, déballage)', 80, NOW(), NOW(), 10, true),
       (56, 'Assistance en marketing d\''influence',
        'Stratégie et gestion des campagnes avec des influenceurs sur les réseaux sociaux', 100, NOW(), NOW(), 52,
        true),
       (57, 'Services de nettoyage de tapis', 'Nettoyage professionnel de tapis et moquettes', 35, NOW(), NOW(), 27,
        true),
       (58, 'Formation en photographie', 'Formation et conseils sur la photographie (techniques, matériel, etc.)', 70,
        NOW(), NOW(), 49, true),
       (59, 'Serrurerie', 'Réparation, installation et ouverture de portes, fenêtres, etc.', 45, NOW(), NOW(), 5, true),
       (60, 'Service de concierge privé',
        'Services personnalisés de conciergerie, réservation de restaurants, gestion d’agenda, etc.', 120, NOW(), NOW(),
        42, true),
       (61, 'Réparation d\''électroménager',
        'Réparation d\''appareils électroménagers de tout type (réfrigérateur, micro-ondes, etc.)', 55, NOW(), NOW(),
        11, true),
       (62, 'Coaching professionnel',
        'Accompagnement pour les professionnels dans la gestion de carrière et le développement personnel', 100, NOW(),
        NOW(), 60, true),
       (63, 'Installation de rideaux et stores', 'Pose de rideaux, stores et autres solutions pour fenêtres', 40, NOW(),
        NOW(), 16, true),
       (64, 'Aménagement d’espaces commerciaux',
        'Conception et aménagement d\''espaces de vente ou de bureaux commerciaux', 90, NOW(), NOW(), 42, true),
       (65, 'Installation de meubles de jardin',
        'Montage et installation de meubles d\''extérieur (tables, chaises, salons de jardin, etc.)', 30, NOW(), NOW(),
        6, true),
       (66, 'Vente de matériel de camping', 'Conseils et vente de matériel pour camping et randonnée', 50, NOW(), NOW(),
        24, true),
       (67, 'Vente d\''accessoires de vélo', 'Vente d\''accessoires pour vélos (casques, gants, porte-bidons, etc.)',
        25, NOW(), NOW(), 25, true),
       (68, 'Réparation de chaussures', 'Réparation et entretien de chaussures (semelles, couture, etc.)', 25, NOW(),
        NOW(), 22, true),
       (69, 'Réparation de smartphones', 'Réparation d\''écrans, batteries et autres composants de téléphones mobiles',
        40, NOW(), NOW(), 1, true),
       (70, 'Soins esthétiques', 'Soins de la peau, maquillage, épilation et autres services esthétiques', 60, NOW(),
        NOW(), 22, true),
       (71, 'Réparation de meubles en bois',
        'Réparation et restauration de meubles en bois (tables, chaises, armoires, etc.)', 45, NOW(), NOW(), 28, true),
       (72, 'Installation de plomberie',
        'Pose de tuyauterie et installation de systèmes de plomberie (éviers, toilettes, etc.)', 55, NOW(), NOW(), 10,
        true),
       (73, 'Équilibrage des pneus', 'Service d\''équilibrage de pneus pour véhicules', 30, NOW(), NOW(), 15, true),
       (74, 'Réparation de PC portables', 'Réparation de PC portables (écrans cassés, pannes de clavier, etc.)', 50,
        NOW(), NOW(), 1, true),
       (75, 'Conception d\''aménagement paysager',
        'Planification et conception de l\''aménagement extérieur (jardins, allées, etc.)', 75, NOW(), NOW(), 6, true),
       (76, 'Gestion des réseaux informatiques',
        'Mise en place, maintenance et gestion des réseaux informatiques pour entreprises', 95, NOW(), NOW(), 4, true),
       (77, 'Service de garde d\''animaux', 'Garde à domicile pour animaux de compagnie, promenades, visites, etc.', 20,
        NOW(), NOW(), 17, true),
       (78, 'Formation en développement personnel', 'Séances de coaching et formation pour le développement personnel',
        70, NOW(), NOW(), 60, true),
       (79, 'Photographie de produits', 'Service de photographie professionnelle pour des produits commerciaux', 80,
        NOW(), NOW(), 49, true),
       (80, 'Rénovation de salle de bain', 'Rénovation complète ou partielle de salles de bains', 90, NOW(), NOW(), 14,
        true);