INSERT INTO favour (id, name_favor, created_at, updated_at, category_id,
                    is_available)
VALUES (1, 'Réparation d’ordinateur', NOW(), NOW(), 1, true),
       (2, 'Installation de systèmes de sécurité',
        NOW(),
        NOW(), 5, true),
       (3, 'Montage de meubles', NOW(), NOW(), 8, true),
       (4, 'Tonte de pelouse', NOW(), NOW(), 6, true),
       (5, 'Peinture intérieure', NOW(), NOW(), 7,
        true),
       (6, 'Soudure métallique', NOW(),
        NOW(), 29, true),
       (7, 'Plomberie générale', NOW(), NOW(),
        10, true),
       (8, 'Réparation de verre', NOW(), NOW(), 3, true),
       (9, 'Vente et installation de panneaux solaires',
        NOW(), NOW(), 12, true),
       (10, 'Maintenance automobile', NOW(), NOW(),
        15, true),
       (11, 'Électricien à domicile',
        NOW(), NOW(), 4, true),
       (12, 'Dépannage informatique', NOW(),
        NOW(), 1, true),
       (13, 'Nettoyage industriel', NOW(), NOW(), 27,
        true),
       (14, 'Installation de climatisation', NOW(),
        NOW(), 13, true),
       (15, 'Pose de carrelage', NOW(), NOW(), 14,
        true),
       (16, 'Création de site web', NOW(), NOW(), 49,
        true),
       (17, 'Design de logos', NOW(), NOW(), 49,
        true),
       (18, 'Création de contenu vidéo', NOW(), NOW(), 23,
        true),
       (19, 'SEO et optimisation de site', NOW(), NOW(), 52, true),
       (20, 'Rédaction d’articles de blog', NOW(), NOW(), 52, true),
       (21, 'Conseil en gestion de projet', NOW(), NOW(), 43, true),
       (22, 'Assistance administrative', NOW(), NOW(), 20, true),
       (23, 'Réparation de téléphone portable', NOW(), NOW(), 1, true),
       (24, 'Service de traduction', NOW(), NOW(), 47, true),
       (25, 'Coaching personnel', NOW(), NOW(), 60, true),
       (26, 'Formation en gestion du temps', NOW(), NOW(), 62, true),
       (27, 'Cours particuliers en mathématiques', NOW(), NOW(), 64, true),
       (28, 'Soutien scolaire', NOW(), NOW(), 64, true),
       (29, 'Photographie événementielle', NOW(), NOW(), 49, true),
       (30, 'Aménagement de bureau', NOW(), NOW(), 21, true),
       (31, 'Création d’applications mobiles', NOW(),
        NOW(), 56, true),
       (32, 'Dépannage de voiture', NOW(), NOW(), 15, true),
       (33, 'Création de stratégie marketing', NOW(), NOW(), 52, true),
       (34, 'Audit de sécurité informatique', NOW(), NOW(), 4, true),
       (35, 'Gestion des réseaux sociaux', NOW(), NOW(), 49, true),
       (36, 'Réparation de toiture', NOW(), NOW(),
        14, true),
       (37, 'Rénovation de cuisine', NOW(), NOW(), 14, true),
       (38, 'Réparation de canalisations', NOW(),
        NOW(), 10, true),
       (39, 'Nettoyage après sinistre', NOW(),
        NOW(), 27, true),
       (40, 'Aménagement de jardin', NOW(),
        NOW(), 6, true),
       (41, 'Coaching de vie', NOW(),
        NOW(), 60, true),
       (42, 'Installation de systèmes d’irrigation',
        NOW(), NOW(), 6, true),
       (43, 'Débouchage de canalisations', NOW(), NOW(), 10,
        true),
       (44, 'Service de baby-sitting', NOW(), NOW(), 17, true),
       (45, 'Événementiel - Organisation de mariage', NOW(), NOW(), 42, true),
       (46, 'Gestion des finances personnelles', NOW(), NOW(), 46, true),
       (47, 'Conseil juridique', NOW(), NOW(), 45, true),
       (48, 'Conseil en marketing digital', NOW(), NOW(), 52, true),
       (49, 'Consultation en image de marque', NOW(), NOW(), 49, true),
       (50, 'Réparation d’appareils électroménagers', NOW(), NOW(), 11, true),
       (51, 'Création de visuels publicitaires', NOW(), NOW(), 49,
        true),
       (52, 'Entretien de piscine', NOW(), NOW(), 6, true),
       (53, 'Livraison de courses', NOW(), NOW(), 22, true),
       (54, 'Formation en Excel', NOW(), NOW(), 52, true),
       (55, 'Déménagement', NOW(), NOW(), 10, true),
       (56, 'Assistance en marketing d\''influence', NOW(), NOW(), 52, true),
       (57, 'Services de nettoyage de tapis', NOW(), NOW(), 27, true),
       (58, 'Formation en photographie', NOW(), NOW(), 49, true),
       (59, 'Serrurerie', NOW(), NOW(), 5, true),
       (60, 'Service de concierge privé', NOW(), NOW(), 42, true),
       (61, 'Réparation d\''électroménager', NOW(), NOW(), 11, true),
       (62, 'Coaching professionnel', NOW(), NOW(), 60, true),
       (63, 'Installation de rideaux et stores', NOW(), NOW(), 16, true),
       (64, 'Aménagement d’espaces commerciaux', NOW(), NOW(), 42, true),
       (65, 'Installation de meubles de jardin', NOW(), NOW(), 6, true),
       (66, 'Vente de matériel de camping', NOW(), NOW(), 24, true),
       (67, 'Vente d\''accessoires de vélo', NOW(), NOW(), 25, true),
       (68, 'Réparation de chaussures', NOW(), NOW(), 22, true),
       (69, 'Réparation de smartphones', NOW(), NOW(), 1, true),
       (70, 'Soins esthétiques', NOW(), NOW(), 22, true),
       (71, 'Réparation de meubles en bois', NOW(), NOW(), 28, true),
       (72, 'Installation de plomberie', NOW(), NOW(), 10, true),
       (73, 'Équilibrage des pneus', NOW(), NOW(), 15, true),
       (74, 'Réparation de PC portables', NOW(), NOW(), 1, true),
       (75, 'Conception d\''aménagement paysager', NOW(), NOW(), 6, true),
       (76, 'Gestion des réseaux informatiques', NOW(), NOW(), 4, true),
       (77, 'Service de garde d\''animaux', NOW(), NOW(), 17, true),
       (78, 'Formation en développement personnel', NOW(), NOW(), 60, true),
       (79, 'Photographie de produits', NOW(), NOW(), 49, true),
       (80, 'Rénovation de salle de bain', NOW(), NOW(), 14, true);