CREATE TABLE favour
(
    id                bigint                 NOT NULL,
    name_favor        character varying(255) NOT NULL,
    description_favor text,
    price_hour_favor  numeric(7, 2)          NOT NULL,
    created_at        timestamp(6) without time zone NOT NULL,
    updated_at        timestamp(6) without time zone,
    category_id       bigint,
    is_available      boolean
);

ALTER TABLE favour
ALTER
COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
      SEQUENCE NAME favour_id_seq
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1
    );

ALTER TABLE favour
    ADD CONSTRAINT favour_pkey PRIMARY KEY (id);

ALTER TABLE favour
    ADD CONSTRAINT favor_to_category
        FOREIGN KEY (category_id)
            REFERENCES categories (id);

ALTER TABLE favour
    ADD CONSTRAINT upDel_favor
        FOREIGN KEY (category_id)
            REFERENCES favour (id)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;