CREATE TABLE user_materials
(
    id          bigint NOT NULL,
    created_at  timestamp(6) without time zone NOT NULL,
    updated_at  timestamp(6) without time zone,
    material_id bigint NOT NULL,
    user_id     bigint NOT NULL
);

ALTER TABLE user_materials
ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME user_materials_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

ALTER TABLE user_materials
    ADD CONSTRAINT user_materials_pkey PRIMARY KEY (id);

ALTER TABLE user_materials
    ADD CONSTRAINT fk_user_material_to_material
        FOREIGN KEY (material_id) REFERENCES materials(id);


ALTER TABLE user_materials
    ADD CONSTRAINT fkuser_material_to_material
        FOREIGN KEY (material_id) REFERENCES materials (id)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;

ALTER TABLE user_materials
    ADD CONSTRAINT fk_user_material_from_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;