INSERT INTO reviews (id, rating, comment, created_at, updated_at, user_favor_id, user_material_id, is_active)
VALUES (1, 4.5, 'Service rapide et très professionnel.', now(), now(), 51, NULL, TRUE),
       (2, 3.0, 'Bonne prestation mais un peu cher.', now(), now(), 52, NULL, TRUE),
       (3, 5.0, 'Parfait, je recommande vivement.', now(), now(), 53, NULL, TRUE),
       (4, 2.5, 'Travail correct mais délai trop long.', now(), now(), 54, NULL, TRUE),
       (5, 4.0, 'Bon rapport qualité/prix.', now(), now(), 55, NULL, TRUE),
       (6, 1.5, 'Le matériel était en mauvais état.', now(), now(), NULL, 1, TRUE),
       (7, 4.2, 'Excellent service, très satisfait.', now(), now(), 56, NULL, TRUE),
       (8, 3.8, 'Correct mais peut mieux faire.', now(), now(), NULL, 2, TRUE),
       (9, 5.0, 'Super expérience, merci beaucoup !', now(), now(), 57, NULL, TRUE),
       (10, 2.0, 'Le matériel ne correspondait pas à la description.', now(), now(), NULL, 3, TRUE),
       (11, 4.7, 'Professionnel et sympathique.', now(), now(), 58, NULL, TRUE),
       (12, 3.5, 'Bon service, mais communication difficile.', now(), now(), 59, NULL, TRUE),
       (13, 4.9, 'Matériel en excellent état.', now(), now(), NULL, 4, TRUE),
       (14, 2.8, 'Un peu déçu par le résultat final.', now(), now(), 60, NULL, TRUE),
       (15, 4.3, 'Rapide et efficace.', now(), now(), NULL, 5, TRUE),
       (16, 3.0, 'Le favor était ponctuel et sympa.', now(), now(), 61, NULL, TRUE),
       (17, 4.0, 'Le matériel a bien fonctionné.', now(), now(), NULL, 6, TRUE),
       (18, 5.0, 'Très bon service, je ferai appel à nouveau.', now(), now(), 62, NULL, TRUE),
       (19, 2.2, 'Le matériel était abîmé.', now(), now(), NULL, 7, TRUE),
       (20, 3.7, 'Service correct mais peut être amélioré.', now(), now(), 63, NULL, TRUE),
       (21, 4.8, 'Très bonne communication et qualité.', now(), now(), NULL, 8, TRUE),
       (22, 1.9, 'Le favor n’est pas venu à l’heure.', now(), now(), 64, NULL, TRUE),
       (23, 4.1, 'Matériel conforme à la description.', now(), now(), NULL, 9, TRUE),
       (24, 3.3, 'Service satisfaisant dans l’ensemble.', now(), now(), 65, NULL, TRUE),
       (25, 4.6, 'Très professionnel et compétent.', now(), now(), NULL, 10, TRUE),
       (26, 2.7, 'Matériel un peu usé.', now(), now(), NULL, 11, TRUE),
       (27, 4.4, 'Favor très agréable et ponctuel.', now(), now(), 66, NULL, TRUE),
       (28, 3.9, 'Matériel utile mais nécessite des réparations.', now(), now(), NULL, 12, TRUE),
       (29, 5.0, 'Service impeccable, je recommande.', now(), now(), 67, NULL, TRUE),
       (30, 2.4, 'Le matériel ne fonctionnait pas bien.', now(), now(), NULL, 13, TRUE),
       (31, 4.0, 'Favor très serviable.', now(), now(), 68, NULL, TRUE),
       (32, 3.6, 'Matériel acceptable pour le prix.', now(), now(), NULL, 14, TRUE),
       (33, 4.7, 'Très bonne expérience avec ce favor.', now(), now(), 69, NULL, TRUE),
       (34, 1.8, 'Matériel défectueux.', now(), now(), NULL, 15, TRUE),
       (35, 4.3, 'Service rapide et efficace.', now(), now(), 70, NULL, TRUE),
       (36, 3.1, 'Matériel correct mais vieillissant.', now(), now(), NULL, 16, TRUE),
       (37, 5.0, 'Favor très professionnel.', now(), now(), 71, NULL, TRUE),
       (38, 2.0, 'Le matériel ne correspondait pas.', now(), now(), NULL, 17, TRUE),
       (39, 4.2, 'Service sympathique et compétent.', now(), now(), 72, NULL, TRUE),
       (40, 3.4, 'Matériel fonctionnel mais à améliorer.', now(), now(), NULL, 18, TRUE),
       (41, 4.9, 'Favor très à l’écoute.', now(), now(), 73, NULL, TRUE),
       (42, 2.6, 'Matériel pas en très bon état.', now(), now(), NULL, 19, TRUE),
       (43, 4.1, 'Service rapide et efficace.', now(), now(), 74, NULL, TRUE),
       (44, 3.2, 'Matériel utilisable mais fragile.', now(), now(), NULL, 20, TRUE),
       (45, 5.0, 'Favor très professionnel et ponctuel.', now(), now(), 75, NULL, TRUE),
       (46, 2.3, 'Matériel défectueux à l’arrivée.', now(), now(), NULL, 21, TRUE),
       (47, 4.5, 'Service de qualité.', now(), now(), 76, NULL, TRUE),
       (48, 3.0, 'Matériel fonctionnel mais usage limité.', now(), now(), NULL, 22, TRUE),
       (49, 4.8, 'Favor très sympathique.', now(), now(), 77, NULL, TRUE),
       (50, 2.1, 'Matériel endommagé.', now(), now(), NULL, 23, TRUE),
       (51, 4.5, 'Service rapide et efficace, très satisfait.', NOW(), NOW(), 1, NULL, true),
       (52, 3.0, 'Produit correct mais un peu cher à mon goût.', NOW(), NOW(), NULL, 2, true),
       (53, 5.0, 'Qualité irréprochable, dépasse mes attentes.', NOW(), NOW(), 3, NULL, true),
       (54, 2.5, 'Résultat décevant, service à améliorer.', NOW(), NOW(), NULL, 4, true),
       (55, 4.0, 'Bon rapport qualité/prix, je recommande.', NOW(), NOW(), 2, NULL, true),
       (56, 3.5, 'Fonctionne bien, mais doit être entretenu régulièrement.', NOW(), NOW(), NULL, 5, true),
       (57, 5.0, 'Très professionnel et courtois, merci !', NOW(), NOW(), 4, NULL, true),
       (58, 1.0, 'Très mauvaise expérience, pas satisfait du tout.', NOW(), NOW(), NULL, 6, true),
       (59, 4.8, 'Produit robuste, idéal pour mes besoins.', NOW(), NOW(), 5, NULL, true),
       (60, 2.0, 'Trop lent et peu fiable.', NOW(), NOW(), NULL, 7, true),
       (61, 4.2, 'Intervention rapide et efficace.', NOW(), NOW(), 6, NULL, true),
       (62, 3.8, 'Conforme à la description, mais un peu fragile.', NOW(), NOW(), NULL, 8, true),
       (63, 5.0, 'Excellente prestation, je suis ravi.', NOW(), NOW(), 7, NULL, true),
       (64, 2.3, 'Service correct mais manque de professionnalisme.', NOW(), NOW(), NULL, 9, true),
       (65, 4.6, 'Produit facile à utiliser et performant.', NOW(), NOW(), 8, NULL, true),
       (66, 3.2, 'Satisfait mais le suivi laisse à désirer.', NOW(), NOW(), NULL, 10, true),
       (67, 5.0, 'Travail soigné et rapide, parfait.', NOW(), NOW(), 9, NULL, true),
       (68, 1.5, 'Problèmes récurrents et manque de réactivité.', NOW(), NOW(), NULL, 11, true),
       (69, 4.4, 'Très bonne qualité pour un prix raisonnable.', NOW(), NOW(), 10, NULL, true),
       (70, 2.8, 'Pas à la hauteur de mes attentes.', NOW(), NOW(), NULL, 12, true),
       (71, 4.9, 'Service clientèle au top, satisfait à 100%.', NOW(), NOW(), 11, NULL, true),
       (72, 3.1, 'Produit acceptable mais pourrait être amélioré.', NOW(), NOW(), NULL, 13, true),
       (73, 5.0, 'Très content de la prestation fournie.', NOW(), NOW(), 12, NULL, true),
       (74, 2.0, 'Manque de professionnalisme et retards fréquents.', NOW(), NOW(), NULL, 14, true),
       (75, 4.3, 'Très bon matériel, conforme à mes attentes.', NOW(), NOW(), 13, NULL, true),
       (76, 3.7, 'Service standard, rien d’exceptionnel.', NOW(), NOW(), NULL, 15, true),
       (77, 5.0, 'Intervention rapide et très efficace.', NOW(), NOW(), 14, NULL, true),
       (78, 1.8, 'Qualité très médiocre, ne pas acheter.', NOW(), NOW(), NULL, 16, true),
       (79, 4.1, 'Matériel fiable et robuste.', NOW(), NOW(), 15, NULL, true),
       (80, 2.6, 'Service moyen, manque d’attention aux détails.', NOW(), NOW(), NULL, 17, true),
       (81, 4.7, 'Excellent rapport qualité/prix.', NOW(), NOW(), 16, NULL, true),
       (82, 3.3, 'Fonctionne bien, mais pas sans défauts.', NOW(), NOW(), NULL, 18, true),
       (83, 5.0, 'Prestation impeccable, je recommande vivement.', NOW(), NOW(), 17, NULL, true),
       (84, 2.1, 'Service insatisfaisant, à éviter.', NOW(), NOW(), NULL, 19, true),
       (85, 4.5, 'Produit très utile et facile à manipuler.', NOW(), NOW(), 18, NULL, true),
       (86, 3.0, 'Conforme mais attendais mieux.', NOW(), NOW(), NULL, 20, true),
       (87, 5.0, 'Travail professionnel et rapide.', NOW(), NOW(), 19, NULL, true),
       (88, 1.2, 'Très mauvaise qualité, à fuir.', NOW(), NOW(), NULL, 21, true),
       (89, 4.4, 'Bon produit, répond bien à mes besoins.', NOW(), NOW(), 20, NULL, true),
       (90, 2.9, 'Satisfaisant mais perfectible.', NOW(), NOW(), NULL, 22, true),
       (91, 4.8, 'Service de qualité, très professionnel.', NOW(), NOW(), 21, NULL, true),
       (92, 3.6, 'Correct mais peut mieux faire.', NOW(), NOW(), NULL, 23, true),
       (93, 5.0, 'Je recommande vivement ce service !', NOW(), NOW(), 22, NULL, true),
       (94, 1.7, 'Intervention décevante, peu sérieux.', NOW(), NOW(), NULL, 24, true),
       (95, 4.2, 'Bon matériel, facile à utiliser.', NOW(), NOW(), 23, NULL, true),
       (96, 3.4, 'Service acceptable.', NOW(), NOW(), NULL, 25, true),
       (97, 5.0, 'Très satisfait du travail effectué.', NOW(), NOW(), 24, NULL, true),
       (98, 2.4, 'Pas assez professionnel, à améliorer.', NOW(), NOW(), NULL, 26, true),
       (99, 4.6, 'Matériel performant et fiable.', NOW(), NOW(), 25, NULL, true),
       (100, 3.9, 'Assez bon, mais pas parfait.', NOW(), NOW(), NULL, 27, true);
